In [5]:
from statsbombpy import sb
import pandas as pd

competitions = sb.competitions()

serie_a = competitions[competitions['competition_name'] == 'Serie A']
serie_a

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
70,12,27,Italy,Serie A,male,False,False,2015/2016,2025-08-15T14:28:50.169562,NaN,NaN,2025-08-15T14:28:50.169562
71,12,86,Italy,Serie A,male,False,False,1986/1987,2025-11-23T11:00:00.442491,NaN,NaN,2025-11-23T11:00:00.442491

In [6]:
matches = sb.matches(competition_id=12, season_id=27)
print(f"Total matches: {len(matches)}")
matches.head(10)
matches[['match_id', 'match_date', 'home_team', 'away_team', 'home_score', 'away_score']]

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Total matches: 380

,match_id,match_date,home_team,away_team,home_score,away_score
0,3879608,2015-11-07,Hellas Verona,Bologna,0,2
1,3879551,2015-09-27,Hellas Verona,Lazio,1,2
2,3879575,2015-10-18,Hellas Verona,Udinese,1,1
3,3879542,2015-09-23,Inter Milan,Hellas Verona,1,0
4,3879600,2015-11-01,Carpi,Hellas Verona,0,0
...,...,...,...,...,...,...
375,3878545,2015-08-23,Sampdoria,Carpi,5,2
376,3878544,2015-08-23,Palermo,Genoa,1,0
377,3878543,2015-08-23,Inter Milan,Atalanta,1,0
378,3878542,2015-08-23,Fiorentina,AC Milan,2,0
379,3878540,2015-08-22,Lazio,Bologna,2,1

In [7]:
events = sb.events(match_id=3878542)
print(f"Total events: {len(events)}")
events['type'].value_counts()

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Total events: 3483

type
Pass               974
Ball Receipt*      943
Carry              731
Pressure           360
Ball Recovery       97
Duel                47
Block               40
Foul Committed      36
Foul Won            36
Miscontrol          29
Goal Keeper         27
Clearance           26
Dribble             23
Shot                23
Interception        20
Dispossessed        17
Dribbled Past       15
Shield               6
Substitution         6
Half Start           4
Half End             4
50/50                4
Injury Stoppage      3
Starting XI          2
Error                2
Bad Behaviour        2
Tactical Shift       2
Player Off           2
Player On            2
Name: count, dtype: int64

In [13]:
#separating x and y and defining shots
shots = events[events['type'] == 'Shot'].copy()

shots['x'] = shots['location'].apply(lambda loc: loc[0])
shots['y'] = shots['location'].apply(lambda loc: loc[1])

shots[['minute', 'team', 'player', 'x', 'y', 'shot_body_part', 'shot_type', 'shot_outcome']].head(10)

,minute,team,player,x,y,shot_body_part,shot_type,shot_outcome
3412,5,Fiorentina,Josip Iličić,88.0,74.8,Right Foot,Open Play,Saved
3413,10,Fiorentina,Josip Iličić,90.3,32.2,Left Foot,Free Kick,Off T
3414,13,AC Milan,Nigel de Jong,94.1,40.4,Right Foot,Open Play,Blocked
3415,13,AC Milan,Giacomo Bonaventura,107.1,31.3,Left Foot,Open Play,Blocked
3416,14,AC Milan,Carlos Arturo Bacca Ahumada,103.7,51.7,Right Foot,Open Play,Off T
3417,15,Fiorentina,Marcos Alonso Mendoza,90.9,22.2,Left Foot,Open Play,Wayward
3418,16,Fiorentina,Milan Badelj,95.2,43.7,Right Foot,Open Play,Blocked
3419,19,Fiorentina,Nikola Kalinić,102.7,36.8,Right Foot,Open Play,Saved
3420,19,Fiorentina,Josip Iličić,100.1,43.5,Left Foot,Open Play,Blocked
3421,20,Fiorentina,Marcos Alonso Mendoza,112.0,21.4,Left Foot,Open Play,Off T

In [14]:
import numpy as np
#calculating distance to goal
#According to StatBomb, the pitch co-ordinates run from (0,0) to (120, 80) [length, width]
#The goal the attack team would be aiming to score would then be located at (120,40) since the goal is usually in the middle of the pitch and at the furthest point away from you length wise.
#hence we can define it like this:
goal_x, goal_y = 120, 40

shots['distance_to_goal'] = np.sqrt((goal_x - shots['x'])**2 + (goal_y - shots['y'])**2)

shots[['x', 'y', 'distance_to_goal']].head(10)

          x     y  distance_to_goal
3412   88.0  74.8         47.276210
3413   90.3  32.2         30.707165
3414   94.1  40.4         25.903089
3415  107.1  31.3         15.559563
3416  103.7  51.7         20.064396
3417   90.9  22.2         34.112314
3418   95.2  43.7         25.074489
3419  102.7  36.8         17.593465
3420  100.1  43.5         20.205445
3421  112.0  21.4         20.247469

In [15]:
# Now we need to calculate angle
#According to StatBomb the goal is 8 units wide. This means 4 on either side from the center which is 40 so we can define it as:
left_post_y, right_post_y = 36, 44

angle_left = np.arctan2(left_post_y - shots['y'], goal_x - shots['x'])
angle_right = np.arctan2(right_post_y - shots['y'], goal_x - shots['x'])

shots['angle_to_goal'] = np.abs(angle_left - angle_right)

shots[['x', 'y', 'distance_to_goal', 'angle_to_goal']].head(10)

          x     y  distance_to_goal  angle_to_goal
3412   88.0  74.8         47.276210       0.114857
3413   90.3  32.2         30.707165       0.250927
3414   94.1  40.4         25.903089       0.306389
3415  107.1  31.3         15.559563       0.428193
3416  103.7  51.7         20.064396       0.325332
3417   90.9  22.2         34.112314       0.200134
3418   95.2  43.7         25.074489       0.313143
3419  102.7  36.8         17.593465       0.440590
3420  100.1  43.5         20.205445       0.385542
3421  112.0  21.4         20.247469       0.161046

In [16]:
shots['is_goal'] = (shots['shot_outcome'] == 'Goal').astype(int)

shots['is_goal'].value_counts()

is_goal
0    21
1     2
Name: count, dtype: int64

In [12]:
all_shots = []
for match_id in matches['match_id']:
    match_events = sb.events(match_id=match_id)
    match_shots = match_events[match_events['type'] == 'Shot'].copy()
    match_shots['match_id'] = match_id
    all_shots.append(match_shots)
    print(f"Match {match_id}: {len(match_shots)} shots")

all_shots_df = pd.concat(all_shots, ignore_index=True)
print(f"\nTotal shots across season: {len(all_shots_df)}")

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879608: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879551: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879575: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879542: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879600: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879557: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879819: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878541: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879664: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879863: 13 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879773: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879847: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879862: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879817: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879825: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879750: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879567: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879785: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879705: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879628: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879665: 36 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879699: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879703: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879609: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879653: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879632: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879663: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879645: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879579: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879566: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879587: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879556: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879585: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879582: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879564: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879562: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879837: 38 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879838: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879839: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879840: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879836: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879833: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879828: 35 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879832: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879830: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879792: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879795: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879794: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879788: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879787: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879786: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879784: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879783: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879782: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879781: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879780: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879779: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879778: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879777: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879774: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879776: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879771: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879772: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879756: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879754: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879748: 35 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879749: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879747: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879742: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879746: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879744: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879745: 38 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879743: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879739: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879741: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879740: 39 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879738: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879737: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879732: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879707: 35 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879702: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879704: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879701: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879700: 35 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879706: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878559: 39 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879636: 34 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879627: 17 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879626: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879625: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879624: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879623: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879622: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879621: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879620: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878611: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878610: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878608: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878607: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878606: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878605: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879876: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879875: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879874: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879873: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879872: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879871: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879870: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879869: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879868: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879867: 42 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879866: 34 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879865: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879864: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879861: 39 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879860: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879859: 42 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879858: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879857: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879856: 34 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879855: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879854: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879853: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879852: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879851: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879850: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879849: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879848: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879846: 39 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879845: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879844: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879843: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879842: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879841: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879835: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879834: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879831: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879829: 34 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879827: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879826: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879824: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879823: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879822: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879821: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879820: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879818: 14 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879816: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879815: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879814: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879813: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879812: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879811: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879810: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879809: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879808: 36 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879807: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879806: 13 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879805: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879804: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879803: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879802: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879801: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879800: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879799: 36 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879798: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879797: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879796: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879793: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879791: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879790: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879789: 39 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879775: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879770: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879769: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879768: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879767: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879766: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879765: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879764: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879763: 40 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879762: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879761: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879760: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879759: 17 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879758: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879757: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879755: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879753: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879752: 35 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879751: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879736: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879735: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879734: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879733: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879731: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879730: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879729: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879728: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879727: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879726: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879725: 36 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879724: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879723: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879722: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879721: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879720: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879719: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879718: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879717: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879716: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879715: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879714: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879713: 36 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879712: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879711: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879710: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879709: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879708: 15 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879698: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879697: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879696: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879695: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879694: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879693: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879692: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879691: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879690: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879689: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879688: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879687: 39 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879686: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879685: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879684: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879683: 40 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879682: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879681: 37 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879680: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879679: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879678: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879677: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879676: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879675: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879674: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879673: 38 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879672: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879671: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879670: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879669: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879668: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879667: 35 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879666: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879662: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879661: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879660: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879659: 14 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879658: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879657: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879656: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879655: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879654: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879652: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879651: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879650: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879649: 36 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879648: 36 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879647: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879646: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879644: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879643: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879642: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879641: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879640: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879639: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879638: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879637: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879635: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879634: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879633: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879631: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879630: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879629: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879619: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879618: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879617: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879616: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879615: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879614: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879613: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879612: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879611: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879610: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879607: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879606: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879605: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879604: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879603: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879602: 37 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879601: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879599: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879598: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879597: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879596: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879595: 11 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879594: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879593: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879592: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879591: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879590: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879589: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879588: 15 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879586: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879584: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879583: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879581: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879580: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879578: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879577: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879576: 34 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879574: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879573: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879572: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879571: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879570: 35 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879569: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879568: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879565: 33 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879563: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879561: 34 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879560: 41 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879559: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879558: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879555: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879554: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879553: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879552: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879550: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879549: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879548: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879547: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879546: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879545: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879544: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879543: 46 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879541: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879540: 15 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879539: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879538: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3879537: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878609: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878604: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878603: 20 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878602: 31 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878601: 21 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878600: 36 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878599: 19 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878598: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878597: 34 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878596: 22 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878595: 26 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878594: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878593: 39 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878592: 24 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878558: 37 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878557: 30 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878556: 18 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878555: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878554: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878553: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878552: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878551: 25 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878550: 16 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878549: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878548: 28 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878547: 39 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878546: 32 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878545: 35 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878544: 29 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878543: 27 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878542: 23 shots

c:\Users\madha\xG-model-football\xG-model-football\venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

Match 3878540: 31 shots

Total shots across season: 9998

In [17]:
print(f"Total matches processed: {len(matches)}")
print(f"Total shots collected: {len(all_shots_df)}")
all_shots_df['is_goal'] = (all_shots_df['shot_outcome'] == 'Goal').astype(int)
print(f"Total goals: {all_shots_df['is_goal'].sum()}")

Total matches processed: 380
Total shots collected: 9998
Total goals: 951

In [18]:
all_shots_df['x'] = all_shots_df['location'].apply(lambda loc: loc[0])
all_shots_df['y'] = all_shots_df['location'].apply(lambda loc: loc[1])

goal_x, goal_y = 120, 40
all_shots_df['distance_to_goal'] = np.sqrt((goal_x - all_shots_df['x'])**2 + (goal_y - all_shots_df['y'])**2)

left_post_y, right_post_y = 36, 44
angle_left = np.arctan2(left_post_y - all_shots_df['y'], goal_x - all_shots_df['x'])
angle_right = np.arctan2(right_post_y - all_shots_df['y'], goal_x - all_shots_df['x'])
all_shots_df['angle_to_goal'] = np.abs(angle_left - angle_right)

all_shots_df[['x', 'y', 'distance_to_goal', 'angle_to_goal', 'is_goal']].head(10)

       x     y  distance_to_goal  angle_to_goal  is_goal
0  106.3  33.1         15.339492       0.463465        0
1   86.6  44.5         33.701780       0.234232        0
2  108.4  32.7         13.705838       0.495138        1
3   95.7  34.8         24.850151       0.312581        0
4  102.8  38.3         17.283807       0.452938        0
5  107.9  47.5         14.235870       0.478409        1
6  103.2  25.2         22.389283       0.270181        0
7  103.2  37.6         16.970563       0.458931        0
8   87.0  32.8         33.776323       0.230528        0
9  109.1  36.9         11.332255       0.659724        0

In [20]:
all_shots_df.to_csv('../data/raw/serie_a_2015_16_shots.csv', index=False)

In [21]:
print(all_shots_df[['distance_to_goal', 'angle_to_goal']].isnull().sum())
all_shots_df['shot_body_part'].value_counts()

distance_to_goal    0
angle_to_goal       0
dtype: int64

shot_body_part
Right Foot    5267
Left Foot     3288
Head          1420
Other           23
Name: count, dtype: int64

In [22]:
model_df = all_shots_df[['distance_to_goal', 'angle_to_goal', 'shot_body_part', 'is_goal']].copy()
model_df = pd.get_dummies(model_df, columns=['shot_body_part'], drop_first=True)
model_df.head()

,distance_to_goal,angle_to_goal,is_goal,shot_body_part_Left Foot,shot_body_part_Other,shot_body_part_Right Foot
0,15.339492,0.463465,0,False,False,False
1,33.701780,0.234232,0,False,False,True
2,13.705838,0.495138,1,True,False,False
3,24.850151,0.312581,0,False,False,True
4,17.283807,0.452938,0,False,False,True